version: '3.2'
services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    depends_on:
    - prom
    volumes:
    - grafana:/var/lib/grafana
  node_exporter:
    image: prom/node-exporter:latest
    container_name: nodeexporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    expose:
      - 9100
  prom:
    image: prom/prometheus:latest
    container_name: prom
    ports:
    - 9090:9090
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    - promdata:/prometheus
    depends_on:
    - postgres_exporter
  postgres_exporter:
    image: wrouesnel/postgres_exporter
    container_name: postgres_exporter
    environment:
    - DATA_SOURCE_NAME=postgresql://postgres:password@postgres:5432/postgres?sslmode=disable
    depends_on:
    - postgres
    ports:
    - 9187:9187
  postgres:
    image: postgres:12
    container_name: postgres
    volumes:
    - pgdata:/var/lib/postgresql/data
    ports:
    - 15432:5432
    environment:
    - POSTGRES_PASSWORD=password


volumes:
  pgdata: {}
  promdata: {}
  grafana: {}